let WORDS=[];
let modeType='time',duration=15,targetWords=25;
let started=false,finished=false,startTime=0,timer=null,currentWords=[],typed='',finalResult=null,history=[];
const $=id=>document.getElementById(id),display=$('words');
const timePresets=[15,30,60,120]; const wordPresets=[10,25,50,100];
async function loadWords(){try{const t=await fetch('words.txt',{cache:'no-store'}).then(r=>r.text());WORDS=t.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}catch(e){WORDS=['the','and','you','that','with','have','this','from','time','more','make','like','work','know','good','right','people','world','life','place','great','small','house','water','light','sound','game','play','type']}newTest()}
function pickWords(n){return Array.from({length:n},()=>WORDS[Math.floor(Math.random()*WORDS.length)])}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function newTest(){clearInterval(timer);timer=null;started=false;finished=false;typed='';finalResult=null;history=[];currentWords=pickWords(modeType==='words'?targetWords:Math.max(500,Math.ceil(duration*5)));$('resultsOverlay').classList.add('hidden');$('wpm').textContent='0';$('raw').textContent='0';$('acc').textContent='100';$('time').textContent=modeType==='words'?targetWords:duration;$('timeUnit').textContent=modeType==='words'?' words':'s';display.focus();render()}
function render(){const charsPerLine=60,lines=[];let line='',start=0,pos=0;currentWords.forEach((word,i)=>{const token=word+(i<currentWords.length-1?' ':'');if(line&&line.length+token.length>charsPerLine){lines.push({text:line,start});line='';start=pos}line+=token;pos+=token.length});if(line)lines.push({text:line,start});let currentLine=0;for(let i=0;i<lines.length;i++){if(typed.length>=lines[i].start&&typed.length<=lines[i].start+lines[i].text.length){currentLine=i;break}}
let html='';lines.forEach((ln,li)=>{let s='';for(let j=0;j<ln.text.length;j++){const idx=ln.start+j,expected=ln.text[j],c=typed[idx];let cls='';if(c!==undefined)cls=c===expected?'correct':'wrong';else if(idx===typed.length)cls='current';s+=`<span class="${cls}">${escapeHtml(expected)}</span>`}html+=`<div class="word-line">${s}</div>`});display.innerHTML=`<div class="word-lines">${html}</div>`;const lh=window.innerWidth<=700?34:42;const y=(display.clientHeight-lh)/2-currentLine*lh;$('.word-lines').style.transform=`translate3d(0,${y}px,0)`}
function metrics(){const elapsed=Math.max((Date.now()-startTime)/1000,.1),expected=currentWords.join(' ');let correct=0;for(let i=0;i<typed.length;i++)if(i<expected.length&&typed[i]===expected[i])correct++;const minutes=elapsed/60;const raw=(typed.length/5)/minutes;const wpm=Math.max(0,(typed.length/5)/minutes-(typed.length-correct)/minutes);const acc=typed.length?correct/typed.length*100:100;return{wpm:Math.round(wpm),raw:Math.round(raw),acc:Math.round(acc),elapsed,correct}}
function recordHistory(){const m=metrics(),t=Math.floor(m.elapsed);const p={t,wpm:m.wpm,raw:m.raw,acc:m.acc};if(!history.length||history.at(-1).t!==t)history.push(p);else history[history.length-1]=p}
function tick(){if(!started||finished)return;recordHistory();const m=metrics();$('wpm').textContent=m.wpm;$('raw').textContent=m.raw;$('acc').textContent=m.acc;if(modeType==='time'){const left=Math.max(0,duration-Math.floor((Date.now()-startTime)/1000));$('time').textContent=left;$('timeUnit').textContent='s';if(left<=0)finish()}else{const done=typed.trim().split(/\s+/).filter(Boolean).length;$('time').textContent=Math.max(0,targetWords-done);$('timeUnit').textContent=' words';if(done>=targetWords)finish()}}
function finish(){if(finished)return;recordHistory();finished=true;clearInterval(timer);timer=null;const m=metrics(),score=Math.max(0,Math.round(m.wpm*m.acc/100));finalResult={wpm:m.wpm,raw:m.raw,acc:m.acc,score,date:new Date().toLocaleString(),duration,mode:modeType,words:targetWords};$('modalWpm').textContent=m.wpm;$('modalRaw').textContent=m.raw;$('modalAcc').textContent=m.acc+'%';$('modalScore').textContent=score;$('resultsSubtitle').textContent=modeType==='time'?`${duration} second test`:`${targetWords} word test`;autoSave();$('resultsOverlay').classList.remove('hidden');requestAnimationFrame(drawGraph);render()}
function autoSave(){const s=JSON.parse(localStorage.getItem('typetap_scores')||'[]');s.push(finalResult);s.sort((a,b)=>b.score-a.score);localStorage.setItem('typetap_scores',JSON.stringify(s.slice(0,100)))}
document.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();newTest();return}if(finished||e.ctrlKey||e.altKey||e.metaKey)return;if(e.key==='Backspace'){e.preventDefault();if(typed.length)typed=typed.slice(0,-1);render();if(started)tick();return}if(e.key.length===1){e.preventDefault();if(!started){started=true;startTime=Date.now();history=[{t:0,wpm:0,raw:0,acc:100}];timer=setInterval(tick,100)}typed+=e.key;const done=typed.trim().split(/\s+/).filter(Boolean).length;if((modeType==='words'&&done>=targetWords)||(modeType==='time'&&typed.length>=currentWords.join(' ').length))finish();else{render();tick()}}});
function closeMenus(){document.querySelectorAll('.dropdown.open').forEach(x=>x.classList.remove('open'))}
function menu(el,container,values,type){container.innerHTML=values.map(v=>`<button data-v="${v}">${v}</button>`).join('')+`<button data-v="custom">custom</button>`;el.onclick=e=>{e.stopPropagation();document.querySelectorAll('.dropdown').forEach(x=>{if(x!==container)x.classList.remove('open')});container.classList.toggle('open')};container.onclick=e=>{const b=e.target.closest('button');if(!b)return;container.classList.remove('open');if(b.dataset.v==='custom'){const n=prompt(type==='time'?'Custom time in seconds:':'Custom word count: ',type==='time'?45:75);const v=Math.max(type==='time'?1:10,Math.min(type==='time'?3600:1000,Number(n)));if(!Number.isFinite(v))return;if(type==='time')duration=Math.round(v);else targetWords=Math.round(v)}else{if(type==='time')duration=+b.dataset.v;else targetWords=+b.dataset.v}setMode(type)} }
menu($('timeMenu'),$('timeOptions'),timePresets,'time');menu($('wordsMenu'),$('wordsOptions'),wordPresets,'words');
function setMode(type){modeType=type;$('timeMenu').classList.toggle('active',type==='time');$('wordsMenu').classList.toggle('active',type==='words');$('timeMenu').querySelector('span').textContent=duration;$('wordsMenu').querySelector('span').textContent=targetWords;newTest()}
document.addEventListener('click',closeMenus);$('restart').onclick=newTest;
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(b.dataset.page).classList.remove('hidden');if(b.dataset.page==='rankings')renderRankings();if(b.dataset.page==='stats')renderStats()});
$('again').onclick=newTest;$('closeResults').onclick=()=>{$('resultsOverlay').classList.add('hidden');newTest()};$('theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('typetap_theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('typetap_theme')==='light')document.body.classList.add('light');window.addEventListener('resize',()=>{render();if(!$('resultsOverlay').classList.contains('hidden'))drawGraph()});
function drawGraph(){const c=$('wpmGraph'),r=c.getBoundingClientRect(),d=window.devicePixelRatio||1,w=r.width,h=r.height;c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);if(!history.length)return;const l=36,rr=12,t=15,b=25,gw=w-l-rr,gh=h-t-b,max=Math.max(20,...history.map(p=>p.raw)),total=Math.max(1,modeType==='time'?duration:history.at(-1).t);x.strokeStyle=getComputedStyle(document.body).getPropertyValue('--grid');for(let i=0;i<4;i++){const y=t+gh*i/3;x.beginPath();x.moveTo(l,y);x.lineTo(w-rr,y);x.stroke()}function series(key,m,style){x.beginPath();history.forEach((p,i)=>{const px=l+p.t/total*gw,py=t+gh-p[key]/m*gh;i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=style;x.lineWidth=2;x.stroke()}series('raw',max,'#8094a8');series('wpm',max,'#4be3ff');series('acc',100,'#ffb84b');}
function scores(){return JSON.parse(localStorage.getItem('typetap_scores')||'[]')};function renderRankings(){const s=scores();$('rankTable').innerHTML=!s.length?'<div class="empty">No tests yet.</div>':'<div class="row head"><span>#</span><span>date</span><span>wpm</span><span>accuracy</span><span>score</span></div>'+s.slice(0,25).map((x,i)=>`<div class="row"><span>${i+1}</span><span>${escapeHtml(x.date)}</span><strong>${x.wpm}</strong><span>${x.acc}%</span><strong>${x.score}</strong></div>`).join('')};function renderStats(){const s=scores();$('count').textContent=s.length;$('best').textContent=s.length?Math.max(...s.map(x=>x.wpm)):0;$('average').textContent=s.length?Math.round(s.reduce((a,x)=>a+x.wpm,0)/s.length):0;$('bestacc').textContent=s.length?Math.max(...s.map(x=>x.acc))+'%':'0%'}
loadWords();
